// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA944GAhZU9jW5qacMTvu5cvgCDE5nl6iY',
    appId: '1:609684986262:web:49b6179c87df134d4665b7',
    messagingSenderId: '609684986262',
    projectId: 'hcsr04-909ec',
    authDomain: 'hcsr04-909ec.firebaseapp.com',
    databaseURL: 'https://hcsr04-909ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hcsr04-909ec.firebasestorage.app',
    measurementId: 'G-CP2WHKY049',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcKnqMs5CQMErHndsEXUHnc3dtN7exq1w',
    appId: '1:609684986262:android:c7004ad2e9631e944665b7',
    messagingSenderId: '609684986262',
    projectId: 'hcsr04-909ec',
    databaseURL: 'https://hcsr04-909ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hcsr04-909ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQcDPX2WSVnIzko_GdZaAne75vIiRvchk',
    appId: '1:609684986262:ios:d48620e56aa74e764665b7',
    messagingSenderId: '609684986262',
    projectId: 'hcsr04-909ec',
    databaseURL: 'https://hcsr04-909ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hcsr04-909ec.firebasestorage.app',
    iosBundleId: 'com.example.myfirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQcDPX2WSVnIzko_GdZaAne75vIiRvchk',
    appId: '1:609684986262:ios:d48620e56aa74e764665b7',
    messagingSenderId: '609684986262',
    projectId: 'hcsr04-909ec',
    databaseURL: 'https://hcsr04-909ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hcsr04-909ec.firebasestorage.app',
    iosBundleId: 'com.example.myfirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA944GAhZU9jW5qacMTvu5cvgCDE5nl6iY',
    appId: '1:609684986262:web:0bfaae91b89c9c6f4665b7',
    messagingSenderId: '609684986262',
    projectId: 'hcsr04-909ec',
    authDomain: 'hcsr04-909ec.firebaseapp.com',
    databaseURL: 'https://hcsr04-909ec-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hcsr04-909ec.firebasestorage.app',
    measurementId: 'G-FXVHRY5PYW',
  );
}
